---
title: "JS Consulting Overall Curriculum Map"
config:
    theme: base
---
flowchart TD
    subgraph anyintro ["<b>Intro Level Courses</b>"]
        intro4["Python Intro <i>4-day</i>"]
        intro["Python Intro <i>5-day</i>"]
        master["Mastering Python <i>5-day</i>"]
        plus["Python Plus <i>3-day</i>"]
        basics["Python Basics <i>3-day</i>"]
    end
    anyintro --> interm["Intermediate Python\n<i>4-day</i>"]
    anyintro --> advanced["Advanced Python\n<i>4-day</i>"]
    anyintro --> djangocomp["Comprehensive Django\n<i>5-day</i>"]
    anyintro --> pysci3day["Python for Scientists\n<i>3-day</i>"]
    pysci["Python for Scientists <i>5-day</i>"] --> interm
    pysci --> advanced
    djangocomp --> advdjango["Advanced Django\n<i>4-day??</i>"]
    djangoboot["Django Boot Camp\n<i>5-day</i>"] --> advdjango
    interm --> extreme["Extreme Python\n<i>5-day</i>"]
    advanced --> extreme
    classDef green fill:#bcf5b8
    class anyintro,pysci,djangoboot green
    classDef blue fill:#bfebf2
    class advanced,interm,pysci3day,djangocomp blue
    classDef red fill:#f5b8c3
    class extreme,advdjango red
