----
Django Packages
----
flowchart TD
    django --> contrib
    contrib --> admin
    contrib --> admindocs
    contrib --> auth
    contrib --> contenttypes
    contrib --> flatpages
    contrib --> gis
    gis --> gisadmin["admin"]
    gis --> gisdb["db"]
    gisdb --> gisbackends["backends"]
    gisdb --> gismodels["models"]
    gis --> gisforms["forms"]
    gis --> gdal
    gis --> geoip2
    gis --> geos
    gis --> gisutils["utils"]
    contrib --> humanize
    contrib --> messages
    contrib --> postgres
    postgres --> aggregates
    contrib --> redirects
    contrib --> sessions
    contrib --> sitemaps
    contrib --> sites
    contrib --> staticfiles
    contrib --> syndication
    django --> apps
    django --> core
    core --> checks
    core --> files
    core --> email
    core --> management
    django --> db
    db --> dbbackends["backends"]
    db --> migrations
    migrations --> operations
    db --> models
    models --> fields
    models --> functions
    django --> dispatch
    django --> forms
    django --> http
    django --> middleware
    django --> template
    template --> tpbackends["backends"]
    django --> test
    django --> urls
    django --> utils
    utils --> translation
    django --> views