flowchart LR
    f(file) --> g1(group)
    f --> d0(dataset)
    g1 --> d1(dataset)
    f --> g2(group)
    g1 --> d2(dataset)
    g2 --> g3(group)
    g3 --> d3(dataset)
    g3 --> d4(dataset)
    g3 --> d5(dataset)






