# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wombats.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WombatParadise(object):
    def setupUi(self, WombatParadise):
        WombatParadise.setObjectName("WombatParadise")
        WombatParadise.resize(812, 445)
        self.centralwidget = QtWidgets.QWidget(WombatParadise)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 671, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        WombatParadise.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WombatParadise)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        WombatParadise.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WombatParadise)
        self.statusbar.setObjectName("statusbar")
        WombatParadise.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(WombatParadise)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(WombatParadise)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(WombatParadise)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCut = QtWidgets.QAction(WombatParadise)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(WombatParadise)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(WombatParadise)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(WombatParadise)
        QtCore.QMetaObject.connectSlotsByName(WombatParadise)

    def retranslateUi(self, WombatParadise):
        _translate = QtCore.QCoreApplication.translate
        WombatParadise.setWindowTitle(_translate("WombatParadise", "MainWindow"))
        self.label.setText(_translate("WombatParadise", "TextLabel"))
        self.pushButton.setText(_translate("WombatParadise", "PushButton"))
        self.menuFile.setTitle(_translate("WombatParadise", "File"))
        self.menuEdit.setTitle(_translate("WombatParadise", "Edit"))
        self.actionOpen.setText(_translate("WombatParadise", "Open"))
        self.actionClose.setText(_translate("WombatParadise", "Close"))
        self.actionQuit.setText(_translate("WombatParadise", "Quit"))
        self.actionCut.setText(_translate("WombatParadise", "Cut"))
        self.actionCopy.setText(_translate("WombatParadise", "Copy"))
        self.actionPaste.setText(_translate("WombatParadise", "Paste"))
